name: Deploy to hungpnh.dev

on:
  push:
    branches:
      - main  # hoặc nhánh bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to hungpnh.dev via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/hungpnh/FE/wedding-site/
            git pull origin main
            npm install
            npm run build
            pm2 restart myapp  # hoặc dotnet run / dotnet myapp.dll nếu dùng .NET
